// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: proto/qimen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QimenService_CalculatePlate_FullMethodName      = "/qimen.QimenService/CalculatePlate"
	QimenService_AnalyzePlate_FullMethodName        = "/qimen.QimenService/AnalyzePlate"
	QimenService_AnalyzeEnhanced_FullMethodName     = "/qimen.QimenService/AnalyzeEnhanced"
	QimenService_GetTeachingSections_FullMethodName = "/qimen.QimenService/GetTeachingSections"
	QimenService_GetCases_FullMethodName            = "/qimen.QimenService/GetCases"
	QimenService_GetPatterns_FullMethodName         = "/qimen.QimenService/GetPatterns"
	QimenService_Health_FullMethodName              = "/qimen.QimenService/Health"
)

// QimenServiceClient is the client API for QimenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 奇門遁甲服務
type QimenServiceClient interface {
	// 排盤 - 計算奇門遁甲盤
	CalculatePlate(ctx context.Context, in *CalculatePlateRequest, opts ...grpc.CallOption) (*CalculatePlateResponse, error)
	// 分析 - 獲取吉凶分析
	AnalyzePlate(ctx context.Context, in *AnalyzePlateRequest, opts ...grpc.CallOption) (*AnalyzePlateResponse, error)
	// 增強分析 - 含三奇六儀+門星神組合
	AnalyzeEnhanced(ctx context.Context, in *AnalyzeEnhancedRequest, opts ...grpc.CallOption) (*AnalyzeEnhancedResponse, error)
	// 教學系統 - 獲取教學內容
	GetTeachingSections(ctx context.Context, in *TeachingRequest, opts ...grpc.CallOption) (*TeachingResponse, error)
	// 案例分析庫 - 獲取經典案例
	GetCases(ctx context.Context, in *CasesRequest, opts ...grpc.CallOption) (*CasesResponse, error)
	// 格局查詢手冊 - 獲取吉凶格局
	GetPatterns(ctx context.Context, in *PatternsRequest, opts ...grpc.CallOption) (*PatternsResponse, error)
	// 健康檢查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type qimenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQimenServiceClient(cc grpc.ClientConnInterface) QimenServiceClient {
	return &qimenServiceClient{cc}
}

func (c *qimenServiceClient) CalculatePlate(ctx context.Context, in *CalculatePlateRequest, opts ...grpc.CallOption) (*CalculatePlateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePlateResponse)
	err := c.cc.Invoke(ctx, QimenService_CalculatePlate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) AnalyzePlate(ctx context.Context, in *AnalyzePlateRequest, opts ...grpc.CallOption) (*AnalyzePlateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzePlateResponse)
	err := c.cc.Invoke(ctx, QimenService_AnalyzePlate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) AnalyzeEnhanced(ctx context.Context, in *AnalyzeEnhancedRequest, opts ...grpc.CallOption) (*AnalyzeEnhancedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeEnhancedResponse)
	err := c.cc.Invoke(ctx, QimenService_AnalyzeEnhanced_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) GetTeachingSections(ctx context.Context, in *TeachingRequest, opts ...grpc.CallOption) (*TeachingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeachingResponse)
	err := c.cc.Invoke(ctx, QimenService_GetTeachingSections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) GetCases(ctx context.Context, in *CasesRequest, opts ...grpc.CallOption) (*CasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CasesResponse)
	err := c.cc.Invoke(ctx, QimenService_GetCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) GetPatterns(ctx context.Context, in *PatternsRequest, opts ...grpc.CallOption) (*PatternsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatternsResponse)
	err := c.cc.Invoke(ctx, QimenService_GetPatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qimenServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, QimenService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QimenServiceServer is the server API for QimenService service.
// All implementations must embed UnimplementedQimenServiceServer
// for forward compatibility.
//
// 奇門遁甲服務
type QimenServiceServer interface {
	// 排盤 - 計算奇門遁甲盤
	CalculatePlate(context.Context, *CalculatePlateRequest) (*CalculatePlateResponse, error)
	// 分析 - 獲取吉凶分析
	AnalyzePlate(context.Context, *AnalyzePlateRequest) (*AnalyzePlateResponse, error)
	// 增強分析 - 含三奇六儀+門星神組合
	AnalyzeEnhanced(context.Context, *AnalyzeEnhancedRequest) (*AnalyzeEnhancedResponse, error)
	// 教學系統 - 獲取教學內容
	GetTeachingSections(context.Context, *TeachingRequest) (*TeachingResponse, error)
	// 案例分析庫 - 獲取經典案例
	GetCases(context.Context, *CasesRequest) (*CasesResponse, error)
	// 格局查詢手冊 - 獲取吉凶格局
	GetPatterns(context.Context, *PatternsRequest) (*PatternsResponse, error)
	// 健康檢查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedQimenServiceServer()
}

// UnimplementedQimenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQimenServiceServer struct{}

func (UnimplementedQimenServiceServer) CalculatePlate(context.Context, *CalculatePlateRequest) (*CalculatePlateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePlate not implemented")
}
func (UnimplementedQimenServiceServer) AnalyzePlate(context.Context, *AnalyzePlateRequest) (*AnalyzePlateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePlate not implemented")
}
func (UnimplementedQimenServiceServer) AnalyzeEnhanced(context.Context, *AnalyzeEnhancedRequest) (*AnalyzeEnhancedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeEnhanced not implemented")
}
func (UnimplementedQimenServiceServer) GetTeachingSections(context.Context, *TeachingRequest) (*TeachingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeachingSections not implemented")
}
func (UnimplementedQimenServiceServer) GetCases(context.Context, *CasesRequest) (*CasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCases not implemented")
}
func (UnimplementedQimenServiceServer) GetPatterns(context.Context, *PatternsRequest) (*PatternsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPatterns not implemented")
}
func (UnimplementedQimenServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedQimenServiceServer) mustEmbedUnimplementedQimenServiceServer() {}
func (UnimplementedQimenServiceServer) testEmbeddedByValue()                      {}

// UnsafeQimenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QimenServiceServer will
// result in compilation errors.
type UnsafeQimenServiceServer interface {
	mustEmbedUnimplementedQimenServiceServer()
}

func RegisterQimenServiceServer(s grpc.ServiceRegistrar, srv QimenServiceServer) {
	// If the following call panics, it indicates UnimplementedQimenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QimenService_ServiceDesc, srv)
}

func _QimenService_CalculatePlate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePlateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).CalculatePlate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_CalculatePlate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).CalculatePlate(ctx, req.(*CalculatePlateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_AnalyzePlate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzePlateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).AnalyzePlate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_AnalyzePlate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).AnalyzePlate(ctx, req.(*AnalyzePlateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_AnalyzeEnhanced_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeEnhancedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).AnalyzeEnhanced(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_AnalyzeEnhanced_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).AnalyzeEnhanced(ctx, req.(*AnalyzeEnhancedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_GetTeachingSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeachingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).GetTeachingSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_GetTeachingSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).GetTeachingSections(ctx, req.(*TeachingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_GetCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).GetCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_GetCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).GetCases(ctx, req.(*CasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_GetPatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).GetPatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_GetPatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).GetPatterns(ctx, req.(*PatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QimenService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QimenServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QimenService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QimenServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QimenService_ServiceDesc is the grpc.ServiceDesc for QimenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QimenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qimen.QimenService",
	HandlerType: (*QimenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePlate",
			Handler:    _QimenService_CalculatePlate_Handler,
		},
		{
			MethodName: "AnalyzePlate",
			Handler:    _QimenService_AnalyzePlate_Handler,
		},
		{
			MethodName: "AnalyzeEnhanced",
			Handler:    _QimenService_AnalyzeEnhanced_Handler,
		},
		{
			MethodName: "GetTeachingSections",
			Handler:    _QimenService_GetTeachingSections_Handler,
		},
		{
			MethodName: "GetCases",
			Handler:    _QimenService_GetCases_Handler,
		},
		{
			MethodName: "GetPatterns",
			Handler:    _QimenService_GetPatterns_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _QimenService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qimen.proto",
}
