// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/qimen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatterType int32

const (
	MatterType_MATTER_TYPE_UNSPECIFIED  MatterType = 0
	MatterType_MATTER_TYPE_GENERAL      MatterType = 1  // 一般綜合
	MatterType_MATTER_TYPE_WEALTH       MatterType = 2  // 財運求財
	MatterType_MATTER_TYPE_CAREER       MatterType = 3  // 官運事業
	MatterType_MATTER_TYPE_TRAVEL       MatterType = 4  // 出行遠行
	MatterType_MATTER_TYPE_HEALTH       MatterType = 5  // 健康疾病
	MatterType_MATTER_TYPE_RELATIONSHIP MatterType = 6  // 人際感情
	MatterType_MATTER_TYPE_STUDY        MatterType = 7  // 學業考試
	MatterType_MATTER_TYPE_LOST         MatterType = 8  // 尋人失物
	MatterType_MATTER_TYPE_LEGAL        MatterType = 9  // 訴訟官非
	MatterType_MATTER_TYPE_PROPERTY     MatterType = 10 // 田宅房產
	MatterType_MATTER_TYPE_MARRIAGE     MatterType = 11 // 婚姻感情
	MatterType_MATTER_TYPE_BUSINESS     MatterType = 12 // 生意投資
	MatterType_MATTER_TYPE_LITIGATION   MatterType = 13 // 爭訟糾紛
)

// Enum value maps for MatterType.
var (
	MatterType_name = map[int32]string{
		0:  "MATTER_TYPE_UNSPECIFIED",
		1:  "MATTER_TYPE_GENERAL",
		2:  "MATTER_TYPE_WEALTH",
		3:  "MATTER_TYPE_CAREER",
		4:  "MATTER_TYPE_TRAVEL",
		5:  "MATTER_TYPE_HEALTH",
		6:  "MATTER_TYPE_RELATIONSHIP",
		7:  "MATTER_TYPE_STUDY",
		8:  "MATTER_TYPE_LOST",
		9:  "MATTER_TYPE_LEGAL",
		10: "MATTER_TYPE_PROPERTY",
		11: "MATTER_TYPE_MARRIAGE",
		12: "MATTER_TYPE_BUSINESS",
		13: "MATTER_TYPE_LITIGATION",
	}
	MatterType_value = map[string]int32{
		"MATTER_TYPE_UNSPECIFIED":  0,
		"MATTER_TYPE_GENERAL":      1,
		"MATTER_TYPE_WEALTH":       2,
		"MATTER_TYPE_CAREER":       3,
		"MATTER_TYPE_TRAVEL":       4,
		"MATTER_TYPE_HEALTH":       5,
		"MATTER_TYPE_RELATIONSHIP": 6,
		"MATTER_TYPE_STUDY":        7,
		"MATTER_TYPE_LOST":         8,
		"MATTER_TYPE_LEGAL":        9,
		"MATTER_TYPE_PROPERTY":     10,
		"MATTER_TYPE_MARRIAGE":     11,
		"MATTER_TYPE_BUSINESS":     12,
		"MATTER_TYPE_LITIGATION":   13,
	}
)

func (x MatterType) Enum() *MatterType {
	p := new(MatterType)
	*p = x
	return p
}

func (x MatterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatterType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qimen_proto_enumTypes[0].Descriptor()
}

func (MatterType) Type() protoreflect.EnumType {
	return &file_proto_qimen_proto_enumTypes[0]
}

func (x MatterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatterType.Descriptor instead.
func (MatterType) EnumDescriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{0}
}

type PatternType int32

const (
	PatternType_PATTERN_TYPE_UNSPECIFIED  PatternType = 0
	PatternType_PATTERN_TYPE_AUSPICIOUS   PatternType = 1 // 大吉格局
	PatternType_PATTERN_TYPE_INAUSPICIOUS PatternType = 2 // 凶格
	PatternType_PATTERN_TYPE_SPECIAL      PatternType = 3 // 特殊格局
	PatternType_PATTERN_TYPE_COMBINATION  PatternType = 4 // 組合格局
)

// Enum value maps for PatternType.
var (
	PatternType_name = map[int32]string{
		0: "PATTERN_TYPE_UNSPECIFIED",
		1: "PATTERN_TYPE_AUSPICIOUS",
		2: "PATTERN_TYPE_INAUSPICIOUS",
		3: "PATTERN_TYPE_SPECIAL",
		4: "PATTERN_TYPE_COMBINATION",
	}
	PatternType_value = map[string]int32{
		"PATTERN_TYPE_UNSPECIFIED":  0,
		"PATTERN_TYPE_AUSPICIOUS":   1,
		"PATTERN_TYPE_INAUSPICIOUS": 2,
		"PATTERN_TYPE_SPECIAL":      3,
		"PATTERN_TYPE_COMBINATION":  4,
	}
)

func (x PatternType) Enum() *PatternType {
	p := new(PatternType)
	*p = x
	return p
}

func (x PatternType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qimen_proto_enumTypes[1].Descriptor()
}

func (PatternType) Type() protoreflect.EnumType {
	return &file_proto_qimen_proto_enumTypes[1]
}

func (x PatternType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatternType.Descriptor instead.
func (PatternType) EnumDescriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{1}
}

type CalculatePlateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                                      // 日期 YYYY-MM-DD，空則使用今天
	Hour          int32                  `protobuf:"varint,2,opt,name=hour,proto3" json:"hour,omitempty"`                                                     // 小時 0-23，空則使用當前小時
	MatterType    MatterType             `protobuf:"varint,3,opt,name=matter_type,json=matterType,proto3,enum=qimen.MatterType" json:"matter_type,omitempty"` // 問事類型
	Liuqin        string                 `protobuf:"bytes,4,opt,name=liuqin,proto3" json:"liuqin,omitempty"`                                                  // 六親關係key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePlateRequest) Reset() {
	*x = CalculatePlateRequest{}
	mi := &file_proto_qimen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePlateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePlateRequest) ProtoMessage() {}

func (x *CalculatePlateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePlateRequest.ProtoReflect.Descriptor instead.
func (*CalculatePlateRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePlateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CalculatePlateRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *CalculatePlateRequest) GetMatterType() MatterType {
	if x != nil {
		return x.MatterType
	}
	return MatterType_MATTER_TYPE_UNSPECIFIED
}

func (x *CalculatePlateRequest) GetLiuqin() string {
	if x != nil {
		return x.Liuqin
	}
	return ""
}

type CalculatePlateResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Success               bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                 string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode             string                  `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Plate                 *QimenPlate             `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
	Meta                  *MetaInfo               `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	PalaceRatingsEnhanced []*PalaceRatingEnhanced `protobuf:"bytes,6,rep,name=palace_ratings_enhanced,json=palaceRatingsEnhanced,proto3" json:"palace_ratings_enhanced,omitempty"`
	PalaceInfo            *PalaceInfo             `protobuf:"bytes,7,opt,name=palace_info,json=palaceInfo,proto3" json:"palace_info,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CalculatePlateResponse) Reset() {
	*x = CalculatePlateResponse{}
	mi := &file_proto_qimen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePlateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePlateResponse) ProtoMessage() {}

func (x *CalculatePlateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePlateResponse.ProtoReflect.Descriptor instead.
func (*CalculatePlateResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePlateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculatePlateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CalculatePlateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CalculatePlateResponse) GetPlate() *QimenPlate {
	if x != nil {
		return x.Plate
	}
	return nil
}

func (x *CalculatePlateResponse) GetMeta() *MetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CalculatePlateResponse) GetPalaceRatingsEnhanced() []*PalaceRatingEnhanced {
	if x != nil {
		return x.PalaceRatingsEnhanced
	}
	return nil
}

func (x *CalculatePlateResponse) GetPalaceInfo() *PalaceInfo {
	if x != nil {
		return x.PalaceInfo
	}
	return nil
}

type AnalyzePlateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Hour          int32                  `protobuf:"varint,2,opt,name=hour,proto3" json:"hour,omitempty"`
	MatterType    MatterType             `protobuf:"varint,3,opt,name=matter_type,json=matterType,proto3,enum=qimen.MatterType" json:"matter_type,omitempty"`
	Liuqin        string                 `protobuf:"bytes,4,opt,name=liuqin,proto3" json:"liuqin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePlateRequest) Reset() {
	*x = AnalyzePlateRequest{}
	mi := &file_proto_qimen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePlateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePlateRequest) ProtoMessage() {}

func (x *AnalyzePlateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePlateRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePlateRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzePlateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AnalyzePlateRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *AnalyzePlateRequest) GetMatterType() MatterType {
	if x != nil {
		return x.MatterType
	}
	return MatterType_MATTER_TYPE_UNSPECIFIED
}

func (x *AnalyzePlateRequest) GetLiuqin() string {
	if x != nil {
		return x.Liuqin
	}
	return ""
}

type AnalyzePlateResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Success               bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                 string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode             string                  `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Plate                 *QimenPlate             `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
	Analysis              *QimenAnalysis          `protobuf:"bytes,5,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Meta                  *MetaInfo               `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	PalaceRatingsEnhanced []*PalaceRatingEnhanced `protobuf:"bytes,7,rep,name=palace_ratings_enhanced,json=palaceRatingsEnhanced,proto3" json:"palace_ratings_enhanced,omitempty"`
	PalaceInfo            *PalaceInfo             `protobuf:"bytes,8,opt,name=palace_info,json=palaceInfo,proto3" json:"palace_info,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AnalyzePlateResponse) Reset() {
	*x = AnalyzePlateResponse{}
	mi := &file_proto_qimen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePlateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePlateResponse) ProtoMessage() {}

func (x *AnalyzePlateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePlateResponse.ProtoReflect.Descriptor instead.
func (*AnalyzePlateResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzePlateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzePlateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalyzePlateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AnalyzePlateResponse) GetPlate() *QimenPlate {
	if x != nil {
		return x.Plate
	}
	return nil
}

func (x *AnalyzePlateResponse) GetAnalysis() *QimenAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *AnalyzePlateResponse) GetMeta() *MetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyzePlateResponse) GetPalaceRatingsEnhanced() []*PalaceRatingEnhanced {
	if x != nil {
		return x.PalaceRatingsEnhanced
	}
	return nil
}

func (x *AnalyzePlateResponse) GetPalaceInfo() *PalaceInfo {
	if x != nil {
		return x.PalaceInfo
	}
	return nil
}

type AnalyzeEnhancedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Hour          int32                  `protobuf:"varint,2,opt,name=hour,proto3" json:"hour,omitempty"`
	MatterType    MatterType             `protobuf:"varint,3,opt,name=matter_type,json=matterType,proto3,enum=qimen.MatterType" json:"matter_type,omitempty"`
	Liuqin        string                 `protobuf:"bytes,4,opt,name=liuqin,proto3" json:"liuqin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeEnhancedRequest) Reset() {
	*x = AnalyzeEnhancedRequest{}
	mi := &file_proto_qimen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeEnhancedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeEnhancedRequest) ProtoMessage() {}

func (x *AnalyzeEnhancedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeEnhancedRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeEnhancedRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeEnhancedRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AnalyzeEnhancedRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *AnalyzeEnhancedRequest) GetMatterType() MatterType {
	if x != nil {
		return x.MatterType
	}
	return MatterType_MATTER_TYPE_UNSPECIFIED
}

func (x *AnalyzeEnhancedRequest) GetLiuqin() string {
	if x != nil {
		return x.Liuqin
	}
	return ""
}

type AnalyzeEnhancedResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Success               bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                 string                  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode             string                  `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Plate                 *QimenPlate             `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
	Analysis              *QimenAnalysis          `protobuf:"bytes,5,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Enhanced              *EnhancedAnalysis       `protobuf:"bytes,6,opt,name=enhanced,proto3" json:"enhanced,omitempty"`
	Meta                  *MetaInfo               `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	PalaceRatingsEnhanced []*PalaceRatingEnhanced `protobuf:"bytes,8,rep,name=palace_ratings_enhanced,json=palaceRatingsEnhanced,proto3" json:"palace_ratings_enhanced,omitempty"`
	PalaceInfo            *PalaceInfo             `protobuf:"bytes,9,opt,name=palace_info,json=palaceInfo,proto3" json:"palace_info,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AnalyzeEnhancedResponse) Reset() {
	*x = AnalyzeEnhancedResponse{}
	mi := &file_proto_qimen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeEnhancedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeEnhancedResponse) ProtoMessage() {}

func (x *AnalyzeEnhancedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeEnhancedResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeEnhancedResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeEnhancedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeEnhancedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AnalyzeEnhancedResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AnalyzeEnhancedResponse) GetPlate() *QimenPlate {
	if x != nil {
		return x.Plate
	}
	return nil
}

func (x *AnalyzeEnhancedResponse) GetAnalysis() *QimenAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *AnalyzeEnhancedResponse) GetEnhanced() *EnhancedAnalysis {
	if x != nil {
		return x.Enhanced
	}
	return nil
}

func (x *AnalyzeEnhancedResponse) GetMeta() *MetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AnalyzeEnhancedResponse) GetPalaceRatingsEnhanced() []*PalaceRatingEnhanced {
	if x != nil {
		return x.PalaceRatingsEnhanced
	}
	return nil
}

func (x *AnalyzeEnhancedResponse) GetPalaceInfo() *PalaceInfo {
	if x != nil {
		return x.PalaceInfo
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_qimen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_qimen_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type QimenPlate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Date        string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	YearGanZhi  string                 `protobuf:"bytes,2,opt,name=year_gan_zhi,json=yearGanZhi,proto3" json:"year_gan_zhi,omitempty"`
	MonthGanZhi string                 `protobuf:"bytes,3,opt,name=month_gan_zhi,json=monthGanZhi,proto3" json:"month_gan_zhi,omitempty"`
	DayGanZhi   string                 `protobuf:"bytes,4,opt,name=day_gan_zhi,json=dayGanZhi,proto3" json:"day_gan_zhi,omitempty"`
	HourGanZhi  string                 `protobuf:"bytes,5,opt,name=hour_gan_zhi,json=hourGanZhi,proto3" json:"hour_gan_zhi,omitempty"`
	Hour        int32                  `protobuf:"varint,6,opt,name=hour,proto3" json:"hour,omitempty"`
	Shichen     string                 `protobuf:"bytes,7,opt,name=shichen,proto3" json:"shichen,omitempty"`                       // 時辰名稱
	JuNumber    int32                  `protobuf:"varint,8,opt,name=ju_number,json=juNumber,proto3" json:"ju_number,omitempty"`    // 局數 1-9
	IsYang      bool                   `protobuf:"varint,9,opt,name=is_yang,json=isYang,proto3" json:"is_yang,omitempty"`          // 是否陽遁
	YinYang     string                 `protobuf:"bytes,10,opt,name=yin_yang,json=yinYang,proto3" json:"yin_yang,omitempty"`       // 陽遁/陰遁
	SolarTerm   string                 `protobuf:"bytes,11,opt,name=solar_term,json=solarTerm,proto3" json:"solar_term,omitempty"` // 節氣
	// 九宮數據 - key 為宮位數字 1-9
	EarthPlate    map[string]string `protobuf:"bytes,12,rep,name=earth_plate,json=earthPlate,proto3" json:"earth_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // 地盤（地盤六儀）
	HeavenPlate   map[string]string `protobuf:"bytes,13,rep,name=heaven_plate,json=heavenPlate,proto3" json:"heaven_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 天盤（天盤三奇六儀）
	HumanPlate    map[string]string `protobuf:"bytes,14,rep,name=human_plate,json=humanPlate,proto3" json:"human_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // 人盤（八門）
	SpiritPlate   map[string]string `protobuf:"bytes,15,rep,name=spirit_plate,json=spiritPlate,proto3" json:"spirit_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 神盤（八神）
	StarsPlate    map[string]string `protobuf:"bytes,16,rep,name=stars_plate,json=starsPlate,proto3" json:"stars_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // 天星盤（九星）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QimenPlate) Reset() {
	*x = QimenPlate{}
	mi := &file_proto_qimen_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QimenPlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QimenPlate) ProtoMessage() {}

func (x *QimenPlate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QimenPlate.ProtoReflect.Descriptor instead.
func (*QimenPlate) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{8}
}

func (x *QimenPlate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *QimenPlate) GetYearGanZhi() string {
	if x != nil {
		return x.YearGanZhi
	}
	return ""
}

func (x *QimenPlate) GetMonthGanZhi() string {
	if x != nil {
		return x.MonthGanZhi
	}
	return ""
}

func (x *QimenPlate) GetDayGanZhi() string {
	if x != nil {
		return x.DayGanZhi
	}
	return ""
}

func (x *QimenPlate) GetHourGanZhi() string {
	if x != nil {
		return x.HourGanZhi
	}
	return ""
}

func (x *QimenPlate) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *QimenPlate) GetShichen() string {
	if x != nil {
		return x.Shichen
	}
	return ""
}

func (x *QimenPlate) GetJuNumber() int32 {
	if x != nil {
		return x.JuNumber
	}
	return 0
}

func (x *QimenPlate) GetIsYang() bool {
	if x != nil {
		return x.IsYang
	}
	return false
}

func (x *QimenPlate) GetYinYang() string {
	if x != nil {
		return x.YinYang
	}
	return ""
}

func (x *QimenPlate) GetSolarTerm() string {
	if x != nil {
		return x.SolarTerm
	}
	return ""
}

func (x *QimenPlate) GetEarthPlate() map[string]string {
	if x != nil {
		return x.EarthPlate
	}
	return nil
}

func (x *QimenPlate) GetHeavenPlate() map[string]string {
	if x != nil {
		return x.HeavenPlate
	}
	return nil
}

func (x *QimenPlate) GetHumanPlate() map[string]string {
	if x != nil {
		return x.HumanPlate
	}
	return nil
}

func (x *QimenPlate) GetSpiritPlate() map[string]string {
	if x != nil {
		return x.SpiritPlate
	}
	return nil
}

func (x *QimenPlate) GetStarsPlate() map[string]string {
	if x != nil {
		return x.StarsPlate
	}
	return nil
}

type PalaceInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CurrentHourPalace     int32                  `protobuf:"varint,1,opt,name=current_hour_palace,json=currentHourPalace,proto3" json:"current_hour_palace,omitempty"`
	CurrentHourPalaceName string                 `protobuf:"bytes,2,opt,name=current_hour_palace_name,json=currentHourPalaceName,proto3" json:"current_hour_palace_name,omitempty"`
	WealthPalace          int32                  `protobuf:"varint,3,opt,name=wealth_palace,json=wealthPalace,proto3" json:"wealth_palace,omitempty"`
	WealthPalaceName      string                 `protobuf:"bytes,4,opt,name=wealth_palace_name,json=wealthPalaceName,proto3" json:"wealth_palace_name,omitempty"`
	CareerPalace          int32                  `protobuf:"varint,5,opt,name=career_palace,json=careerPalace,proto3" json:"career_palace,omitempty"`
	CareerPalaceName      string                 `protobuf:"bytes,6,opt,name=career_palace_name,json=careerPalaceName,proto3" json:"career_palace_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PalaceInfo) Reset() {
	*x = PalaceInfo{}
	mi := &file_proto_qimen_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceInfo) ProtoMessage() {}

func (x *PalaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceInfo.ProtoReflect.Descriptor instead.
func (*PalaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{9}
}

func (x *PalaceInfo) GetCurrentHourPalace() int32 {
	if x != nil {
		return x.CurrentHourPalace
	}
	return 0
}

func (x *PalaceInfo) GetCurrentHourPalaceName() string {
	if x != nil {
		return x.CurrentHourPalaceName
	}
	return ""
}

func (x *PalaceInfo) GetWealthPalace() int32 {
	if x != nil {
		return x.WealthPalace
	}
	return 0
}

func (x *PalaceInfo) GetWealthPalaceName() string {
	if x != nil {
		return x.WealthPalaceName
	}
	return ""
}

func (x *PalaceInfo) GetCareerPalace() int32 {
	if x != nil {
		return x.CareerPalace
	}
	return 0
}

func (x *PalaceInfo) GetCareerPalaceName() string {
	if x != nil {
		return x.CareerPalaceName
	}
	return ""
}

type PalaceRatingEnhanced struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PalaceIndex       int32                  `protobuf:"varint,1,opt,name=palace_index,json=palaceIndex,proto3" json:"palace_index,omitempty"`
	PalaceName        string                 `protobuf:"bytes,2,opt,name=palace_name,json=palaceName,proto3" json:"palace_name,omitempty"`
	OverallScore      int32                  `protobuf:"varint,3,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	WealthScore       int32                  `protobuf:"varint,4,opt,name=wealth_score,json=wealthScore,proto3" json:"wealth_score,omitempty"`
	CareerScore       int32                  `protobuf:"varint,5,opt,name=career_score,json=careerScore,proto3" json:"career_score,omitempty"`
	HealthScore       int32                  `protobuf:"varint,6,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	RelationshipScore int32                  `protobuf:"varint,7,opt,name=relationship_score,json=relationshipScore,proto3" json:"relationship_score,omitempty"`
	StudyScore        int32                  `protobuf:"varint,8,opt,name=study_score,json=studyScore,proto3" json:"study_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PalaceRatingEnhanced) Reset() {
	*x = PalaceRatingEnhanced{}
	mi := &file_proto_qimen_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceRatingEnhanced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceRatingEnhanced) ProtoMessage() {}

func (x *PalaceRatingEnhanced) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceRatingEnhanced.ProtoReflect.Descriptor instead.
func (*PalaceRatingEnhanced) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{10}
}

func (x *PalaceRatingEnhanced) GetPalaceIndex() int32 {
	if x != nil {
		return x.PalaceIndex
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetPalaceName() string {
	if x != nil {
		return x.PalaceName
	}
	return ""
}

func (x *PalaceRatingEnhanced) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetWealthScore() int32 {
	if x != nil {
		return x.WealthScore
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetCareerScore() int32 {
	if x != nil {
		return x.CareerScore
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetHealthScore() int32 {
	if x != nil {
		return x.HealthScore
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetRelationshipScore() int32 {
	if x != nil {
		return x.RelationshipScore
	}
	return 0
}

func (x *PalaceRatingEnhanced) GetStudyScore() int32 {
	if x != nil {
		return x.StudyScore
	}
	return 0
}

type QimenAnalysis struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OverallLevel    string                 `protobuf:"bytes,1,opt,name=overall_level,json=overallLevel,proto3" json:"overall_level,omitempty"`  // 整體吉凶等級
	OverallScore    int32                  `protobuf:"varint,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"` // 整體分數 0-100
	Recommendations []string               `protobuf:"bytes,3,rep,name=recommendations,proto3" json:"recommendations,omitempty"`                // 建議事項
	// 九宮評分 - key 為宮位數字
	PalaceRatings map[string]*PalaceRating `protobuf:"bytes,4,rep,name=palace_ratings,json=palaceRatings,proto3" json:"palace_ratings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 三奇六儀分析
	QiyiAnalysis []string `protobuf:"bytes,5,rep,name=qiyi_analysis,json=qiyiAnalysis,proto3" json:"qiyi_analysis,omitempty"`
	// 門星組合亮點
	DoorStarHighlights []string `protobuf:"bytes,6,rep,name=door_star_highlights,json=doorStarHighlights,proto3" json:"door_star_highlights,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QimenAnalysis) Reset() {
	*x = QimenAnalysis{}
	mi := &file_proto_qimen_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QimenAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QimenAnalysis) ProtoMessage() {}

func (x *QimenAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QimenAnalysis.ProtoReflect.Descriptor instead.
func (*QimenAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{11}
}

func (x *QimenAnalysis) GetOverallLevel() string {
	if x != nil {
		return x.OverallLevel
	}
	return ""
}

func (x *QimenAnalysis) GetOverallScore() int32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *QimenAnalysis) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *QimenAnalysis) GetPalaceRatings() map[string]*PalaceRating {
	if x != nil {
		return x.PalaceRatings
	}
	return nil
}

func (x *QimenAnalysis) GetQiyiAnalysis() []string {
	if x != nil {
		return x.QiyiAnalysis
	}
	return nil
}

func (x *QimenAnalysis) GetDoorStarHighlights() []string {
	if x != nil {
		return x.DoorStarHighlights
	}
	return nil
}

type PalaceRating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`         // 大吉/吉/平/凶/大凶
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`        // 分數 0-100
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`     // 評語摘要
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"` // 方位（如：北）
	Trigram       string                 `protobuf:"bytes,5,opt,name=trigram,proto3" json:"trigram,omitempty"`     // 八卦（如：坎）
	Element       string                 `protobuf:"bytes,6,opt,name=element,proto3" json:"element,omitempty"`     // 五行（如：水）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PalaceRating) Reset() {
	*x = PalaceRating{}
	mi := &file_proto_qimen_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceRating) ProtoMessage() {}

func (x *PalaceRating) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceRating.ProtoReflect.Descriptor instead.
func (*PalaceRating) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{12}
}

func (x *PalaceRating) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PalaceRating) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PalaceRating) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PalaceRating) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PalaceRating) GetTrigram() string {
	if x != nil {
		return x.Trigram
	}
	return ""
}

func (x *PalaceRating) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type EnhancedAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 九宮增強分析
	Palaces       map[string]*PalaceEnhanced `protobuf:"bytes,1,rep,name=palaces,proto3" json:"palaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhancedAnalysis) Reset() {
	*x = EnhancedAnalysis{}
	mi := &file_proto_qimen_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhancedAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhancedAnalysis) ProtoMessage() {}

func (x *EnhancedAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhancedAnalysis.ProtoReflect.Descriptor instead.
func (*EnhancedAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{13}
}

func (x *EnhancedAnalysis) GetPalaces() map[string]*PalaceEnhanced {
	if x != nil {
		return x.Palaces
	}
	return nil
}

type PalaceEnhanced struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 三奇六儀解讀
	QiyiMeanings []string `protobuf:"bytes,1,rep,name=qiyi_meanings,json=qiyiMeanings,proto3" json:"qiyi_meanings,omitempty"`
	// 門星組合解讀
	DoorStarCombinations []string `protobuf:"bytes,2,rep,name=door_star_combinations,json=doorStarCombinations,proto3" json:"door_star_combinations,omitempty"`
	// 門神組合解讀
	DoorSpiritCombinations []string `protobuf:"bytes,3,rep,name=door_spirit_combinations,json=doorSpiritCombinations,proto3" json:"door_spirit_combinations,omitempty"`
	// 星神組合解讀
	StarSpiritCombinations []string `protobuf:"bytes,4,rep,name=star_spirit_combinations,json=starSpiritCombinations,proto3" json:"star_spirit_combinations,omitempty"`
	// 特殊格局
	SpecialPatterns []string `protobuf:"bytes,5,rep,name=special_patterns,json=specialPatterns,proto3" json:"special_patterns,omitempty"`
	// 詳細建議
	DetailedAdvice []string `protobuf:"bytes,6,rep,name=detailed_advice,json=detailedAdvice,proto3" json:"detailed_advice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PalaceEnhanced) Reset() {
	*x = PalaceEnhanced{}
	mi := &file_proto_qimen_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PalaceEnhanced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PalaceEnhanced) ProtoMessage() {}

func (x *PalaceEnhanced) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PalaceEnhanced.ProtoReflect.Descriptor instead.
func (*PalaceEnhanced) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{14}
}

func (x *PalaceEnhanced) GetQiyiMeanings() []string {
	if x != nil {
		return x.QiyiMeanings
	}
	return nil
}

func (x *PalaceEnhanced) GetDoorStarCombinations() []string {
	if x != nil {
		return x.DoorStarCombinations
	}
	return nil
}

func (x *PalaceEnhanced) GetDoorSpiritCombinations() []string {
	if x != nil {
		return x.DoorSpiritCombinations
	}
	return nil
}

func (x *PalaceEnhanced) GetStarSpiritCombinations() []string {
	if x != nil {
		return x.StarSpiritCombinations
	}
	return nil
}

func (x *PalaceEnhanced) GetSpecialPatterns() []string {
	if x != nil {
		return x.SpecialPatterns
	}
	return nil
}

func (x *PalaceEnhanced) GetDetailedAdvice() []string {
	if x != nil {
		return x.DetailedAdvice
	}
	return nil
}

type MetaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaInfo) Reset() {
	*x = MetaInfo{}
	mi := &file_proto_qimen_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaInfo) ProtoMessage() {}

func (x *MetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaInfo.ProtoReflect.Descriptor instead.
func (*MetaInfo) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{15}
}

func (x *MetaInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MetaInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetaInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type TeachingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     string                 `protobuf:"bytes,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"` // 選填，無則返回全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeachingRequest) Reset() {
	*x = TeachingRequest{}
	mi := &file_proto_qimen_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingRequest) ProtoMessage() {}

func (x *TeachingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingRequest.ProtoReflect.Descriptor instead.
func (*TeachingRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{16}
}

func (x *TeachingRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

type TeachingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Sections      []*TeachingSection     `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeachingResponse) Reset() {
	*x = TeachingResponse{}
	mi := &file_proto_qimen_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingResponse) ProtoMessage() {}

func (x *TeachingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingResponse.ProtoReflect.Descriptor instead.
func (*TeachingResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{17}
}

func (x *TeachingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TeachingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TeachingResponse) GetSections() []*TeachingSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *TeachingResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TeachingSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Contents      []*TeachingContent     `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeachingSection) Reset() {
	*x = TeachingSection{}
	mi := &file_proto_qimen_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingSection) ProtoMessage() {}

func (x *TeachingSection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingSection.ProtoReflect.Descriptor instead.
func (*TeachingSection) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{18}
}

func (x *TeachingSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeachingSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TeachingSection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TeachingSection) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TeachingSection) GetContents() []*TeachingContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

type TeachingContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text/highlight/list/table
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	HighlightType string                 `protobuf:"bytes,3,opt,name=highlight_type,json=highlightType,proto3" json:"highlight_type,omitempty"` // info/warning/success
	Items         []string               `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                                      // for list type
	Rows          []*TableRow            `protobuf:"bytes,5,rep,name=rows,proto3" json:"rows,omitempty"`                                        // for table type
	Headers       []string               `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`                                  // for table type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeachingContent) Reset() {
	*x = TeachingContent{}
	mi := &file_proto_qimen_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeachingContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeachingContent) ProtoMessage() {}

func (x *TeachingContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeachingContent.ProtoReflect.Descriptor instead.
func (*TeachingContent) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{19}
}

func (x *TeachingContent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TeachingContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TeachingContent) GetHighlightType() string {
	if x != nil {
		return x.HighlightType
	}
	return ""
}

func (x *TeachingContent) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TeachingContent) GetRows() []*TableRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TeachingContent) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type TableRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRow) Reset() {
	*x = TableRow{}
	mi := &file_proto_qimen_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRow) ProtoMessage() {}

func (x *TableRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRow.ProtoReflect.Descriptor instead.
func (*TableRow) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{20}
}

func (x *TableRow) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

type CasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`                                    // 選填
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`                                                        // 標籤篩選
	MatterType    MatterType             `protobuf:"varint,3,opt,name=matter_type,json=matterType,proto3,enum=qimen.MatterType" json:"matter_type,omitempty"` // 問事類型篩選
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`                                                  // 關鍵字搜尋
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasesRequest) Reset() {
	*x = CasesRequest{}
	mi := &file_proto_qimen_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasesRequest) ProtoMessage() {}

func (x *CasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasesRequest.ProtoReflect.Descriptor instead.
func (*CasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{21}
}

func (x *CasesRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CasesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CasesRequest) GetMatterType() MatterType {
	if x != nil {
		return x.MatterType
	}
	return MatterType_MATTER_TYPE_UNSPECIFIED
}

func (x *CasesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type CasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Cases         []*CaseStudy           `protobuf:"bytes,3,rep,name=cases,proto3" json:"cases,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CasesResponse) Reset() {
	*x = CasesResponse{}
	mi := &file_proto_qimen_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasesResponse) ProtoMessage() {}

func (x *CasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasesResponse.ProtoReflect.Descriptor instead.
func (*CasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{22}
}

func (x *CasesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CasesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CasesResponse) GetCases() []*CaseStudy {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *CasesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CasesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CaseStudy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Hour          string                 `protobuf:"bytes,5,opt,name=hour,proto3" json:"hour,omitempty"`
	SolarTerm     string                 `protobuf:"bytes,6,opt,name=solar_term,json=solarTerm,proto3" json:"solar_term,omitempty"`
	JuNumber      int32                  `protobuf:"varint,7,opt,name=ju_number,json=juNumber,proto3" json:"ju_number,omitempty"`
	YinYang       string                 `protobuf:"bytes,8,opt,name=yin_yang,json=yinYang,proto3" json:"yin_yang,omitempty"`
	MatterType    MatterType             `protobuf:"varint,9,opt,name=matter_type,json=matterType,proto3,enum=qimen.MatterType" json:"matter_type,omitempty"`
	Question      string                 `protobuf:"bytes,10,opt,name=question,proto3" json:"question,omitempty"`
	Background    string                 `protobuf:"bytes,11,opt,name=background,proto3" json:"background,omitempty"`
	PlateSnapshot *PlateSnapshot         `protobuf:"bytes,12,opt,name=plate_snapshot,json=plateSnapshot,proto3" json:"plate_snapshot,omitempty"`
	Analysis      *CaseAnalysis          `protobuf:"bytes,13,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Conclusion    string                 `protobuf:"bytes,14,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	Lessons       []string               `protobuf:"bytes,15,rep,name=lessons,proto3" json:"lessons,omitempty"`
	Tags          []string               `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseStudy) Reset() {
	*x = CaseStudy{}
	mi := &file_proto_qimen_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseStudy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseStudy) ProtoMessage() {}

func (x *CaseStudy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseStudy.ProtoReflect.Descriptor instead.
func (*CaseStudy) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{23}
}

func (x *CaseStudy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaseStudy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CaseStudy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CaseStudy) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CaseStudy) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *CaseStudy) GetSolarTerm() string {
	if x != nil {
		return x.SolarTerm
	}
	return ""
}

func (x *CaseStudy) GetJuNumber() int32 {
	if x != nil {
		return x.JuNumber
	}
	return 0
}

func (x *CaseStudy) GetYinYang() string {
	if x != nil {
		return x.YinYang
	}
	return ""
}

func (x *CaseStudy) GetMatterType() MatterType {
	if x != nil {
		return x.MatterType
	}
	return MatterType_MATTER_TYPE_UNSPECIFIED
}

func (x *CaseStudy) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CaseStudy) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *CaseStudy) GetPlateSnapshot() *PlateSnapshot {
	if x != nil {
		return x.PlateSnapshot
	}
	return nil
}

func (x *CaseStudy) GetAnalysis() *CaseAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *CaseStudy) GetConclusion() string {
	if x != nil {
		return x.Conclusion
	}
	return ""
}

func (x *CaseStudy) GetLessons() []string {
	if x != nil {
		return x.Lessons
	}
	return nil
}

func (x *CaseStudy) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PlateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeavenPlate   map[string]string      `protobuf:"bytes,1,rep,name=heaven_plate,json=heavenPlate,proto3" json:"heaven_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HumanPlate    map[string]string      `protobuf:"bytes,2,rep,name=human_plate,json=humanPlate,proto3" json:"human_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SpiritPlate   map[string]string      `protobuf:"bytes,3,rep,name=spirit_plate,json=spiritPlate,proto3" json:"spirit_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StarsPlate    map[string]string      `protobuf:"bytes,4,rep,name=stars_plate,json=starsPlate,proto3" json:"stars_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EarthPlate    map[string]string      `protobuf:"bytes,5,rep,name=earth_plate,json=earthPlate,proto3" json:"earth_plate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlateSnapshot) Reset() {
	*x = PlateSnapshot{}
	mi := &file_proto_qimen_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateSnapshot) ProtoMessage() {}

func (x *PlateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateSnapshot.ProtoReflect.Descriptor instead.
func (*PlateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{24}
}

func (x *PlateSnapshot) GetHeavenPlate() map[string]string {
	if x != nil {
		return x.HeavenPlate
	}
	return nil
}

func (x *PlateSnapshot) GetHumanPlate() map[string]string {
	if x != nil {
		return x.HumanPlate
	}
	return nil
}

func (x *PlateSnapshot) GetSpiritPlate() map[string]string {
	if x != nil {
		return x.SpiritPlate
	}
	return nil
}

func (x *PlateSnapshot) GetStarsPlate() map[string]string {
	if x != nil {
		return x.StarsPlate
	}
	return nil
}

func (x *PlateSnapshot) GetEarthPlate() map[string]string {
	if x != nil {
		return x.EarthPlate
	}
	return nil
}

type CaseAnalysis struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GodPalace         int32                  `protobuf:"varint,1,opt,name=god_palace,json=godPalace,proto3" json:"god_palace,omitempty"`
	PalaceAnalysis    string                 `protobuf:"bytes,2,opt,name=palace_analysis,json=palaceAnalysis,proto3" json:"palace_analysis,omitempty"`
	ElementAnalysis   string                 `protobuf:"bytes,3,opt,name=element_analysis,json=elementAnalysis,proto3" json:"element_analysis,omitempty"`
	TimingAnalysis    string                 `protobuf:"bytes,4,opt,name=timing_analysis,json=timingAnalysis,proto3" json:"timing_analysis,omitempty"`
	DirectionAnalysis string                 `protobuf:"bytes,5,opt,name=direction_analysis,json=directionAnalysis,proto3" json:"direction_analysis,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CaseAnalysis) Reset() {
	*x = CaseAnalysis{}
	mi := &file_proto_qimen_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseAnalysis) ProtoMessage() {}

func (x *CaseAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseAnalysis.ProtoReflect.Descriptor instead.
func (*CaseAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{25}
}

func (x *CaseAnalysis) GetGodPalace() int32 {
	if x != nil {
		return x.GodPalace
	}
	return 0
}

func (x *CaseAnalysis) GetPalaceAnalysis() string {
	if x != nil {
		return x.PalaceAnalysis
	}
	return ""
}

func (x *CaseAnalysis) GetElementAnalysis() string {
	if x != nil {
		return x.ElementAnalysis
	}
	return ""
}

func (x *CaseAnalysis) GetTimingAnalysis() string {
	if x != nil {
		return x.TimingAnalysis
	}
	return ""
}

func (x *CaseAnalysis) GetDirectionAnalysis() string {
	if x != nil {
		return x.DirectionAnalysis
	}
	return ""
}

type PatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatternId     string                 `protobuf:"bytes,1,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id,omitempty"` // 選填
	Type          PatternType            `protobuf:"varint,2,opt,name=type,proto3,enum=qimen.PatternType" json:"type,omitempty"`    // 格局類型篩選
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`                        // 關鍵字搜尋
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternsRequest) Reset() {
	*x = PatternsRequest{}
	mi := &file_proto_qimen_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternsRequest) ProtoMessage() {}

func (x *PatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternsRequest.ProtoReflect.Descriptor instead.
func (*PatternsRequest) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{26}
}

func (x *PatternsRequest) GetPatternId() string {
	if x != nil {
		return x.PatternId
	}
	return ""
}

func (x *PatternsRequest) GetType() PatternType {
	if x != nil {
		return x.Type
	}
	return PatternType_PATTERN_TYPE_UNSPECIFIED
}

func (x *PatternsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type PatternsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Patterns      []*QimenPattern        `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Total         int32                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternsResponse) Reset() {
	*x = PatternsResponse{}
	mi := &file_proto_qimen_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternsResponse) ProtoMessage() {}

func (x *PatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternsResponse.ProtoReflect.Descriptor instead.
func (*PatternsResponse) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{27}
}

func (x *PatternsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PatternsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PatternsResponse) GetPatterns() []*QimenPattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *PatternsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PatternsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QimenPattern struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type              PatternType            `protobuf:"varint,3,opt,name=type,proto3,enum=qimen.PatternType" json:"type,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Conditions        []string               `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Interpretation    string                 `protobuf:"bytes,6,opt,name=interpretation,proto3" json:"interpretation,omitempty"`
	ApplicableMatters []string               `protobuf:"bytes,7,rep,name=applicable_matters,json=applicableMatters,proto3" json:"applicable_matters,omitempty"`
	Remedies          string                 `protobuf:"bytes,8,opt,name=remedies,proto3" json:"remedies,omitempty"`
	Examples          []string               `protobuf:"bytes,9,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QimenPattern) Reset() {
	*x = QimenPattern{}
	mi := &file_proto_qimen_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QimenPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QimenPattern) ProtoMessage() {}

func (x *QimenPattern) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qimen_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QimenPattern.ProtoReflect.Descriptor instead.
func (*QimenPattern) Descriptor() ([]byte, []int) {
	return file_proto_qimen_proto_rawDescGZIP(), []int{28}
}

func (x *QimenPattern) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QimenPattern) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QimenPattern) GetType() PatternType {
	if x != nil {
		return x.Type
	}
	return PatternType_PATTERN_TYPE_UNSPECIFIED
}

func (x *QimenPattern) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QimenPattern) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *QimenPattern) GetInterpretation() string {
	if x != nil {
		return x.Interpretation
	}
	return ""
}

func (x *QimenPattern) GetApplicableMatters() []string {
	if x != nil {
		return x.ApplicableMatters
	}
	return nil
}

func (x *QimenPattern) GetRemedies() string {
	if x != nil {
		return x.Remedies
	}
	return ""
}

func (x *QimenPattern) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

var File_proto_qimen_proto protoreflect.FileDescriptor

const file_proto_qimen_proto_rawDesc = "" +
	"\n" +
	"\x11proto/qimen.proto\x12\x05qimen\"\x8b\x01\n" +
	"\x15CalculatePlateRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\x05R\x04hour\x122\n" +
	"\vmatter_type\x18\x03 \x01(\x0e2\x11.qimen.MatterTypeR\n" +
	"matterType\x12\x16\n" +
	"\x06liuqin\x18\x04 \x01(\tR\x06liuqin\"\xbe\x02\n" +
	"\x16CalculatePlateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12'\n" +
	"\x05plate\x18\x04 \x01(\v2\x11.qimen.QimenPlateR\x05plate\x12#\n" +
	"\x04meta\x18\x05 \x01(\v2\x0f.qimen.MetaInfoR\x04meta\x12S\n" +
	"\x17palace_ratings_enhanced\x18\x06 \x03(\v2\x1b.qimen.PalaceRatingEnhancedR\x15palaceRatingsEnhanced\x122\n" +
	"\vpalace_info\x18\a \x01(\v2\x11.qimen.PalaceInfoR\n" +
	"palaceInfo\"\x89\x01\n" +
	"\x13AnalyzePlateRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\x05R\x04hour\x122\n" +
	"\vmatter_type\x18\x03 \x01(\x0e2\x11.qimen.MatterTypeR\n" +
	"matterType\x12\x16\n" +
	"\x06liuqin\x18\x04 \x01(\tR\x06liuqin\"\xee\x02\n" +
	"\x14AnalyzePlateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12'\n" +
	"\x05plate\x18\x04 \x01(\v2\x11.qimen.QimenPlateR\x05plate\x120\n" +
	"\banalysis\x18\x05 \x01(\v2\x14.qimen.QimenAnalysisR\banalysis\x12#\n" +
	"\x04meta\x18\x06 \x01(\v2\x0f.qimen.MetaInfoR\x04meta\x12S\n" +
	"\x17palace_ratings_enhanced\x18\a \x03(\v2\x1b.qimen.PalaceRatingEnhancedR\x15palaceRatingsEnhanced\x122\n" +
	"\vpalace_info\x18\b \x01(\v2\x11.qimen.PalaceInfoR\n" +
	"palaceInfo\"\x8c\x01\n" +
	"\x16AnalyzeEnhancedRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\x05R\x04hour\x122\n" +
	"\vmatter_type\x18\x03 \x01(\x0e2\x11.qimen.MatterTypeR\n" +
	"matterType\x12\x16\n" +
	"\x06liuqin\x18\x04 \x01(\tR\x06liuqin\"\xa6\x03\n" +
	"\x17AnalyzeEnhancedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12'\n" +
	"\x05plate\x18\x04 \x01(\v2\x11.qimen.QimenPlateR\x05plate\x120\n" +
	"\banalysis\x18\x05 \x01(\v2\x14.qimen.QimenAnalysisR\banalysis\x123\n" +
	"\benhanced\x18\x06 \x01(\v2\x17.qimen.EnhancedAnalysisR\benhanced\x12#\n" +
	"\x04meta\x18\a \x01(\v2\x0f.qimen.MetaInfoR\x04meta\x12S\n" +
	"\x17palace_ratings_enhanced\x18\b \x03(\v2\x1b.qimen.PalaceRatingEnhancedR\x15palaceRatingsEnhanced\x122\n" +
	"\vpalace_info\x18\t \x01(\v2\x11.qimen.PalaceInfoR\n" +
	"palaceInfo\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xdd\a\n" +
	"\n" +
	"QimenPlate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12 \n" +
	"\fyear_gan_zhi\x18\x02 \x01(\tR\n" +
	"yearGanZhi\x12\"\n" +
	"\rmonth_gan_zhi\x18\x03 \x01(\tR\vmonthGanZhi\x12\x1e\n" +
	"\vday_gan_zhi\x18\x04 \x01(\tR\tdayGanZhi\x12 \n" +
	"\fhour_gan_zhi\x18\x05 \x01(\tR\n" +
	"hourGanZhi\x12\x12\n" +
	"\x04hour\x18\x06 \x01(\x05R\x04hour\x12\x18\n" +
	"\ashichen\x18\a \x01(\tR\ashichen\x12\x1b\n" +
	"\tju_number\x18\b \x01(\x05R\bjuNumber\x12\x17\n" +
	"\ais_yang\x18\t \x01(\bR\x06isYang\x12\x19\n" +
	"\byin_yang\x18\n" +
	" \x01(\tR\ayinYang\x12\x1d\n" +
	"\n" +
	"solar_term\x18\v \x01(\tR\tsolarTerm\x12B\n" +
	"\vearth_plate\x18\f \x03(\v2!.qimen.QimenPlate.EarthPlateEntryR\n" +
	"earthPlate\x12E\n" +
	"\fheaven_plate\x18\r \x03(\v2\".qimen.QimenPlate.HeavenPlateEntryR\vheavenPlate\x12B\n" +
	"\vhuman_plate\x18\x0e \x03(\v2!.qimen.QimenPlate.HumanPlateEntryR\n" +
	"humanPlate\x12E\n" +
	"\fspirit_plate\x18\x0f \x03(\v2\".qimen.QimenPlate.SpiritPlateEntryR\vspiritPlate\x12B\n" +
	"\vstars_plate\x18\x10 \x03(\v2!.qimen.QimenPlate.StarsPlateEntryR\n" +
	"starsPlate\x1a=\n" +
	"\x0fEarthPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10HeavenPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fHumanPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10SpiritPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fStarsPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x02\n" +
	"\n" +
	"PalaceInfo\x12.\n" +
	"\x13current_hour_palace\x18\x01 \x01(\x05R\x11currentHourPalace\x127\n" +
	"\x18current_hour_palace_name\x18\x02 \x01(\tR\x15currentHourPalaceName\x12#\n" +
	"\rwealth_palace\x18\x03 \x01(\x05R\fwealthPalace\x12,\n" +
	"\x12wealth_palace_name\x18\x04 \x01(\tR\x10wealthPalaceName\x12#\n" +
	"\rcareer_palace\x18\x05 \x01(\x05R\fcareerPalace\x12,\n" +
	"\x12career_palace_name\x18\x06 \x01(\tR\x10careerPalaceName\"\xb8\x02\n" +
	"\x14PalaceRatingEnhanced\x12!\n" +
	"\fpalace_index\x18\x01 \x01(\x05R\vpalaceIndex\x12\x1f\n" +
	"\vpalace_name\x18\x02 \x01(\tR\n" +
	"palaceName\x12#\n" +
	"\roverall_score\x18\x03 \x01(\x05R\foverallScore\x12!\n" +
	"\fwealth_score\x18\x04 \x01(\x05R\vwealthScore\x12!\n" +
	"\fcareer_score\x18\x05 \x01(\x05R\vcareerScore\x12!\n" +
	"\fhealth_score\x18\x06 \x01(\x05R\vhealthScore\x12-\n" +
	"\x12relationship_score\x18\a \x01(\x05R\x11relationshipScore\x12\x1f\n" +
	"\vstudy_score\x18\b \x01(\x05R\n" +
	"studyScore\"\x81\x03\n" +
	"\rQimenAnalysis\x12#\n" +
	"\roverall_level\x18\x01 \x01(\tR\foverallLevel\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x05R\foverallScore\x12(\n" +
	"\x0frecommendations\x18\x03 \x03(\tR\x0frecommendations\x12N\n" +
	"\x0epalace_ratings\x18\x04 \x03(\v2'.qimen.QimenAnalysis.PalaceRatingsEntryR\rpalaceRatings\x12#\n" +
	"\rqiyi_analysis\x18\x05 \x03(\tR\fqiyiAnalysis\x120\n" +
	"\x14door_star_highlights\x18\x06 \x03(\tR\x12doorStarHighlights\x1aU\n" +
	"\x12PalaceRatingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.qimen.PalaceRatingR\x05value:\x028\x01\"\xa6\x01\n" +
	"\fPalaceRating\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x18\n" +
	"\atrigram\x18\x05 \x01(\tR\atrigram\x12\x18\n" +
	"\aelement\x18\x06 \x01(\tR\aelement\"\xa5\x01\n" +
	"\x10EnhancedAnalysis\x12>\n" +
	"\apalaces\x18\x01 \x03(\v2$.qimen.EnhancedAnalysis.PalacesEntryR\apalaces\x1aQ\n" +
	"\fPalacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.qimen.PalaceEnhancedR\x05value:\x028\x01\"\xb3\x02\n" +
	"\x0ePalaceEnhanced\x12#\n" +
	"\rqiyi_meanings\x18\x01 \x03(\tR\fqiyiMeanings\x124\n" +
	"\x16door_star_combinations\x18\x02 \x03(\tR\x14doorStarCombinations\x128\n" +
	"\x18door_spirit_combinations\x18\x03 \x03(\tR\x16doorSpiritCombinations\x128\n" +
	"\x18star_spirit_combinations\x18\x04 \x03(\tR\x16starSpiritCombinations\x12)\n" +
	"\x10special_patterns\x18\x05 \x03(\tR\x0fspecialPatterns\x12'\n" +
	"\x0fdetailed_advice\x18\x06 \x03(\tR\x0edetailedAdvice\"V\n" +
	"\bMetaInfo\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"0\n" +
	"\x0fTeachingRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\tR\tsectionId\"\x8c\x01\n" +
	"\x10TeachingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x122\n" +
	"\bsections\x18\x03 \x03(\v2\x16.qimen.TeachingSectionR\bsections\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"\xa3\x01\n" +
	"\x0fTeachingSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x122\n" +
	"\bcontents\x18\x05 \x03(\v2\x16.qimen.TeachingContentR\bcontents\"\xbb\x01\n" +
	"\x0fTeachingContent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12%\n" +
	"\x0ehighlight_type\x18\x03 \x01(\tR\rhighlightType\x12\x14\n" +
	"\x05items\x18\x04 \x03(\tR\x05items\x12#\n" +
	"\x04rows\x18\x05 \x03(\v2\x0f.qimen.TableRowR\x04rows\x12\x18\n" +
	"\aheaders\x18\x06 \x03(\tR\aheaders\" \n" +
	"\bTableRow\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"\x85\x01\n" +
	"\fCasesRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x122\n" +
	"\vmatter_type\x18\x03 \x01(\x0e2\x11.qimen.MatterTypeR\n" +
	"matterType\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\x93\x01\n" +
	"\rCasesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x05cases\x18\x03 \x03(\v2\x10.qimen.CaseStudyR\x05cases\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\xfe\x03\n" +
	"\tCaseStudy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12\x12\n" +
	"\x04hour\x18\x05 \x01(\tR\x04hour\x12\x1d\n" +
	"\n" +
	"solar_term\x18\x06 \x01(\tR\tsolarTerm\x12\x1b\n" +
	"\tju_number\x18\a \x01(\x05R\bjuNumber\x12\x19\n" +
	"\byin_yang\x18\b \x01(\tR\ayinYang\x122\n" +
	"\vmatter_type\x18\t \x01(\x0e2\x11.qimen.MatterTypeR\n" +
	"matterType\x12\x1a\n" +
	"\bquestion\x18\n" +
	" \x01(\tR\bquestion\x12\x1e\n" +
	"\n" +
	"background\x18\v \x01(\tR\n" +
	"background\x12;\n" +
	"\x0eplate_snapshot\x18\f \x01(\v2\x14.qimen.PlateSnapshotR\rplateSnapshot\x12/\n" +
	"\banalysis\x18\r \x01(\v2\x13.qimen.CaseAnalysisR\banalysis\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x0e \x01(\tR\n" +
	"conclusion\x12\x18\n" +
	"\alessons\x18\x0f \x03(\tR\alessons\x12\x12\n" +
	"\x04tags\x18\x10 \x03(\tR\x04tags\"\xb5\x05\n" +
	"\rPlateSnapshot\x12H\n" +
	"\fheaven_plate\x18\x01 \x03(\v2%.qimen.PlateSnapshot.HeavenPlateEntryR\vheavenPlate\x12E\n" +
	"\vhuman_plate\x18\x02 \x03(\v2$.qimen.PlateSnapshot.HumanPlateEntryR\n" +
	"humanPlate\x12H\n" +
	"\fspirit_plate\x18\x03 \x03(\v2%.qimen.PlateSnapshot.SpiritPlateEntryR\vspiritPlate\x12E\n" +
	"\vstars_plate\x18\x04 \x03(\v2$.qimen.PlateSnapshot.StarsPlateEntryR\n" +
	"starsPlate\x12E\n" +
	"\vearth_plate\x18\x05 \x03(\v2$.qimen.PlateSnapshot.EarthPlateEntryR\n" +
	"earthPlate\x1a>\n" +
	"\x10HeavenPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fHumanPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10SpiritPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fStarsPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fEarthPlateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\fCaseAnalysis\x12\x1d\n" +
	"\n" +
	"god_palace\x18\x01 \x01(\x05R\tgodPalace\x12'\n" +
	"\x0fpalace_analysis\x18\x02 \x01(\tR\x0epalaceAnalysis\x12)\n" +
	"\x10element_analysis\x18\x03 \x01(\tR\x0felementAnalysis\x12'\n" +
	"\x0ftiming_analysis\x18\x04 \x01(\tR\x0etimingAnalysis\x12-\n" +
	"\x12direction_analysis\x18\x05 \x01(\tR\x11directionAnalysis\"p\n" +
	"\x0fPatternsRequest\x12\x1d\n" +
	"\n" +
	"pattern_id\x18\x01 \x01(\tR\tpatternId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.qimen.PatternTypeR\x04type\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x9f\x01\n" +
	"\x10PatternsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12/\n" +
	"\bpatterns\x18\x03 \x03(\v2\x13.qimen.QimenPatternR\bpatterns\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x05R\x05total\"\xab\x02\n" +
	"\fQimenPattern\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.qimen.PatternTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x03(\tR\n" +
	"conditions\x12&\n" +
	"\x0einterpretation\x18\x06 \x01(\tR\x0einterpretation\x12-\n" +
	"\x12applicable_matters\x18\a \x03(\tR\x11applicableMatters\x12\x1a\n" +
	"\bremedies\x18\b \x01(\tR\bremedies\x12\x1a\n" +
	"\bexamples\x18\t \x03(\tR\bexamples*\xee\x02\n" +
	"\n" +
	"MatterType\x12\x1b\n" +
	"\x17MATTER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MATTER_TYPE_GENERAL\x10\x01\x12\x16\n" +
	"\x12MATTER_TYPE_WEALTH\x10\x02\x12\x16\n" +
	"\x12MATTER_TYPE_CAREER\x10\x03\x12\x16\n" +
	"\x12MATTER_TYPE_TRAVEL\x10\x04\x12\x16\n" +
	"\x12MATTER_TYPE_HEALTH\x10\x05\x12\x1c\n" +
	"\x18MATTER_TYPE_RELATIONSHIP\x10\x06\x12\x15\n" +
	"\x11MATTER_TYPE_STUDY\x10\a\x12\x14\n" +
	"\x10MATTER_TYPE_LOST\x10\b\x12\x15\n" +
	"\x11MATTER_TYPE_LEGAL\x10\t\x12\x18\n" +
	"\x14MATTER_TYPE_PROPERTY\x10\n" +
	"\x12\x18\n" +
	"\x14MATTER_TYPE_MARRIAGE\x10\v\x12\x18\n" +
	"\x14MATTER_TYPE_BUSINESS\x10\f\x12\x1a\n" +
	"\x16MATTER_TYPE_LITIGATION\x10\r*\x9f\x01\n" +
	"\vPatternType\x12\x1c\n" +
	"\x18PATTERN_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PATTERN_TYPE_AUSPICIOUS\x10\x01\x12\x1d\n" +
	"\x19PATTERN_TYPE_INAUSPICIOUS\x10\x02\x12\x18\n" +
	"\x14PATTERN_TYPE_SPECIAL\x10\x03\x12\x1c\n" +
	"\x18PATTERN_TYPE_COMBINATION\x10\x042\xee\x03\n" +
	"\fQimenService\x12M\n" +
	"\x0eCalculatePlate\x12\x1c.qimen.CalculatePlateRequest\x1a\x1d.qimen.CalculatePlateResponse\x12G\n" +
	"\fAnalyzePlate\x12\x1a.qimen.AnalyzePlateRequest\x1a\x1b.qimen.AnalyzePlateResponse\x12P\n" +
	"\x0fAnalyzeEnhanced\x12\x1d.qimen.AnalyzeEnhancedRequest\x1a\x1e.qimen.AnalyzeEnhancedResponse\x12F\n" +
	"\x13GetTeachingSections\x12\x16.qimen.TeachingRequest\x1a\x17.qimen.TeachingResponse\x125\n" +
	"\bGetCases\x12\x13.qimen.CasesRequest\x1a\x14.qimen.CasesResponse\x12>\n" +
	"\vGetPatterns\x12\x16.qimen.PatternsRequest\x1a\x17.qimen.PatternsResponse\x125\n" +
	"\x06Health\x12\x14.qimen.HealthRequest\x1a\x15.qimen.HealthResponseB<\n" +
	"\x0fcom.qimen.protoZ)github.com/kaecer68/qimen-zenith/v2/protob\x06proto3"

var (
	file_proto_qimen_proto_rawDescOnce sync.Once
	file_proto_qimen_proto_rawDescData []byte
)

func file_proto_qimen_proto_rawDescGZIP() []byte {
	file_proto_qimen_proto_rawDescOnce.Do(func() {
		file_proto_qimen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qimen_proto_rawDesc), len(file_proto_qimen_proto_rawDesc)))
	})
	return file_proto_qimen_proto_rawDescData
}

var file_proto_qimen_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_qimen_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_proto_qimen_proto_goTypes = []any{
	(MatterType)(0),                 // 0: qimen.MatterType
	(PatternType)(0),                // 1: qimen.PatternType
	(*CalculatePlateRequest)(nil),   // 2: qimen.CalculatePlateRequest
	(*CalculatePlateResponse)(nil),  // 3: qimen.CalculatePlateResponse
	(*AnalyzePlateRequest)(nil),     // 4: qimen.AnalyzePlateRequest
	(*AnalyzePlateResponse)(nil),    // 5: qimen.AnalyzePlateResponse
	(*AnalyzeEnhancedRequest)(nil),  // 6: qimen.AnalyzeEnhancedRequest
	(*AnalyzeEnhancedResponse)(nil), // 7: qimen.AnalyzeEnhancedResponse
	(*HealthRequest)(nil),           // 8: qimen.HealthRequest
	(*HealthResponse)(nil),          // 9: qimen.HealthResponse
	(*QimenPlate)(nil),              // 10: qimen.QimenPlate
	(*PalaceInfo)(nil),              // 11: qimen.PalaceInfo
	(*PalaceRatingEnhanced)(nil),    // 12: qimen.PalaceRatingEnhanced
	(*QimenAnalysis)(nil),           // 13: qimen.QimenAnalysis
	(*PalaceRating)(nil),            // 14: qimen.PalaceRating
	(*EnhancedAnalysis)(nil),        // 15: qimen.EnhancedAnalysis
	(*PalaceEnhanced)(nil),          // 16: qimen.PalaceEnhanced
	(*MetaInfo)(nil),                // 17: qimen.MetaInfo
	(*TeachingRequest)(nil),         // 18: qimen.TeachingRequest
	(*TeachingResponse)(nil),        // 19: qimen.TeachingResponse
	(*TeachingSection)(nil),         // 20: qimen.TeachingSection
	(*TeachingContent)(nil),         // 21: qimen.TeachingContent
	(*TableRow)(nil),                // 22: qimen.TableRow
	(*CasesRequest)(nil),            // 23: qimen.CasesRequest
	(*CasesResponse)(nil),           // 24: qimen.CasesResponse
	(*CaseStudy)(nil),               // 25: qimen.CaseStudy
	(*PlateSnapshot)(nil),           // 26: qimen.PlateSnapshot
	(*CaseAnalysis)(nil),            // 27: qimen.CaseAnalysis
	(*PatternsRequest)(nil),         // 28: qimen.PatternsRequest
	(*PatternsResponse)(nil),        // 29: qimen.PatternsResponse
	(*QimenPattern)(nil),            // 30: qimen.QimenPattern
	nil,                             // 31: qimen.QimenPlate.EarthPlateEntry
	nil,                             // 32: qimen.QimenPlate.HeavenPlateEntry
	nil,                             // 33: qimen.QimenPlate.HumanPlateEntry
	nil,                             // 34: qimen.QimenPlate.SpiritPlateEntry
	nil,                             // 35: qimen.QimenPlate.StarsPlateEntry
	nil,                             // 36: qimen.QimenAnalysis.PalaceRatingsEntry
	nil,                             // 37: qimen.EnhancedAnalysis.PalacesEntry
	nil,                             // 38: qimen.PlateSnapshot.HeavenPlateEntry
	nil,                             // 39: qimen.PlateSnapshot.HumanPlateEntry
	nil,                             // 40: qimen.PlateSnapshot.SpiritPlateEntry
	nil,                             // 41: qimen.PlateSnapshot.StarsPlateEntry
	nil,                             // 42: qimen.PlateSnapshot.EarthPlateEntry
}
var file_proto_qimen_proto_depIdxs = []int32{
	0,  // 0: qimen.CalculatePlateRequest.matter_type:type_name -> qimen.MatterType
	10, // 1: qimen.CalculatePlateResponse.plate:type_name -> qimen.QimenPlate
	17, // 2: qimen.CalculatePlateResponse.meta:type_name -> qimen.MetaInfo
	12, // 3: qimen.CalculatePlateResponse.palace_ratings_enhanced:type_name -> qimen.PalaceRatingEnhanced
	11, // 4: qimen.CalculatePlateResponse.palace_info:type_name -> qimen.PalaceInfo
	0,  // 5: qimen.AnalyzePlateRequest.matter_type:type_name -> qimen.MatterType
	10, // 6: qimen.AnalyzePlateResponse.plate:type_name -> qimen.QimenPlate
	13, // 7: qimen.AnalyzePlateResponse.analysis:type_name -> qimen.QimenAnalysis
	17, // 8: qimen.AnalyzePlateResponse.meta:type_name -> qimen.MetaInfo
	12, // 9: qimen.AnalyzePlateResponse.palace_ratings_enhanced:type_name -> qimen.PalaceRatingEnhanced
	11, // 10: qimen.AnalyzePlateResponse.palace_info:type_name -> qimen.PalaceInfo
	0,  // 11: qimen.AnalyzeEnhancedRequest.matter_type:type_name -> qimen.MatterType
	10, // 12: qimen.AnalyzeEnhancedResponse.plate:type_name -> qimen.QimenPlate
	13, // 13: qimen.AnalyzeEnhancedResponse.analysis:type_name -> qimen.QimenAnalysis
	15, // 14: qimen.AnalyzeEnhancedResponse.enhanced:type_name -> qimen.EnhancedAnalysis
	17, // 15: qimen.AnalyzeEnhancedResponse.meta:type_name -> qimen.MetaInfo
	12, // 16: qimen.AnalyzeEnhancedResponse.palace_ratings_enhanced:type_name -> qimen.PalaceRatingEnhanced
	11, // 17: qimen.AnalyzeEnhancedResponse.palace_info:type_name -> qimen.PalaceInfo
	31, // 18: qimen.QimenPlate.earth_plate:type_name -> qimen.QimenPlate.EarthPlateEntry
	32, // 19: qimen.QimenPlate.heaven_plate:type_name -> qimen.QimenPlate.HeavenPlateEntry
	33, // 20: qimen.QimenPlate.human_plate:type_name -> qimen.QimenPlate.HumanPlateEntry
	34, // 21: qimen.QimenPlate.spirit_plate:type_name -> qimen.QimenPlate.SpiritPlateEntry
	35, // 22: qimen.QimenPlate.stars_plate:type_name -> qimen.QimenPlate.StarsPlateEntry
	36, // 23: qimen.QimenAnalysis.palace_ratings:type_name -> qimen.QimenAnalysis.PalaceRatingsEntry
	37, // 24: qimen.EnhancedAnalysis.palaces:type_name -> qimen.EnhancedAnalysis.PalacesEntry
	20, // 25: qimen.TeachingResponse.sections:type_name -> qimen.TeachingSection
	21, // 26: qimen.TeachingSection.contents:type_name -> qimen.TeachingContent
	22, // 27: qimen.TeachingContent.rows:type_name -> qimen.TableRow
	0,  // 28: qimen.CasesRequest.matter_type:type_name -> qimen.MatterType
	25, // 29: qimen.CasesResponse.cases:type_name -> qimen.CaseStudy
	0,  // 30: qimen.CaseStudy.matter_type:type_name -> qimen.MatterType
	26, // 31: qimen.CaseStudy.plate_snapshot:type_name -> qimen.PlateSnapshot
	27, // 32: qimen.CaseStudy.analysis:type_name -> qimen.CaseAnalysis
	38, // 33: qimen.PlateSnapshot.heaven_plate:type_name -> qimen.PlateSnapshot.HeavenPlateEntry
	39, // 34: qimen.PlateSnapshot.human_plate:type_name -> qimen.PlateSnapshot.HumanPlateEntry
	40, // 35: qimen.PlateSnapshot.spirit_plate:type_name -> qimen.PlateSnapshot.SpiritPlateEntry
	41, // 36: qimen.PlateSnapshot.stars_plate:type_name -> qimen.PlateSnapshot.StarsPlateEntry
	42, // 37: qimen.PlateSnapshot.earth_plate:type_name -> qimen.PlateSnapshot.EarthPlateEntry
	1,  // 38: qimen.PatternsRequest.type:type_name -> qimen.PatternType
	30, // 39: qimen.PatternsResponse.patterns:type_name -> qimen.QimenPattern
	1,  // 40: qimen.QimenPattern.type:type_name -> qimen.PatternType
	14, // 41: qimen.QimenAnalysis.PalaceRatingsEntry.value:type_name -> qimen.PalaceRating
	16, // 42: qimen.EnhancedAnalysis.PalacesEntry.value:type_name -> qimen.PalaceEnhanced
	2,  // 43: qimen.QimenService.CalculatePlate:input_type -> qimen.CalculatePlateRequest
	4,  // 44: qimen.QimenService.AnalyzePlate:input_type -> qimen.AnalyzePlateRequest
	6,  // 45: qimen.QimenService.AnalyzeEnhanced:input_type -> qimen.AnalyzeEnhancedRequest
	18, // 46: qimen.QimenService.GetTeachingSections:input_type -> qimen.TeachingRequest
	23, // 47: qimen.QimenService.GetCases:input_type -> qimen.CasesRequest
	28, // 48: qimen.QimenService.GetPatterns:input_type -> qimen.PatternsRequest
	8,  // 49: qimen.QimenService.Health:input_type -> qimen.HealthRequest
	3,  // 50: qimen.QimenService.CalculatePlate:output_type -> qimen.CalculatePlateResponse
	5,  // 51: qimen.QimenService.AnalyzePlate:output_type -> qimen.AnalyzePlateResponse
	7,  // 52: qimen.QimenService.AnalyzeEnhanced:output_type -> qimen.AnalyzeEnhancedResponse
	19, // 53: qimen.QimenService.GetTeachingSections:output_type -> qimen.TeachingResponse
	24, // 54: qimen.QimenService.GetCases:output_type -> qimen.CasesResponse
	29, // 55: qimen.QimenService.GetPatterns:output_type -> qimen.PatternsResponse
	9,  // 56: qimen.QimenService.Health:output_type -> qimen.HealthResponse
	50, // [50:57] is the sub-list for method output_type
	43, // [43:50] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_proto_qimen_proto_init() }
func file_proto_qimen_proto_init() {
	if File_proto_qimen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qimen_proto_rawDesc), len(file_proto_qimen_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qimen_proto_goTypes,
		DependencyIndexes: file_proto_qimen_proto_depIdxs,
		EnumInfos:         file_proto_qimen_proto_enumTypes,
		MessageInfos:      file_proto_qimen_proto_msgTypes,
	}.Build()
	File_proto_qimen_proto = out.File
	file_proto_qimen_proto_goTypes = nil
	file_proto_qimen_proto_depIdxs = nil
}
